# Generated by Django 5.0 on 2024-12-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(max_length=50)),
                ('posted_date', models.DateTimeField()),
                ('is_remote', models.BooleanField(default=False)),
                ('company_logo_url', models.URLField(blank=True, null=True)),
                ('application_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
