# Generated by Django 5.0 on 2024-12-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
